- name: Install Android SDK + Build-tools + NDK
        run: |
          rm -rf .buildozer
          rm -rf $HOME/android-sdk
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk

          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d cmdline-tools-temp

          mkdir -p cmdline-tools/latest
          mv cmdline-tools-temp/cmdline-tools/* cmdline-tools/latest/

          chmod +x cmdline-tools/latest/bin/*

          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools"
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-33"
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "build-tools;33.0.2"
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "ndk;25.2.9519653"

          # 🔧 FIX DEFINITIU: Buildozer necessita aquesta carpeta per detectar el SDK extern
          mkdir -p $HOME/android-sdk/build-tools/33.0.2
