name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev python3-pip
          pip3 install --user --upgrade buildozer

      - name: Build with Buildozer
        run: |
          # Ejecutamos Buildozer sin el 'yes |' para evitar el Broken Pipe
          # Añadimos -v para que el log nos diga exactamente qué hace
          buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
